export const industries = [
  {
    title: "Amusement Park",
    categories: [
      "Family-Owned Theme Park",
      "Regional Park",
      "Water Park",
      "Carnival",
      "Family-Fun Park",
      "Funfair",
      "Educational Theme Park",
    ],
  },
  {
    title: "Apparel",
    categories: [
      "Department Store",
      "Supermarket Store",
      "Discount Store",
      "Fast Fashion",
    ],
  },
  {
    title: "Aquarium",
    categories: [
      "Saltwater",
      "Freshwater",
      "Aviaries",
      "Aquatic Petting Zoo",
      "Dolphins",
      "Sharks",
      "Whales",
      "Otters",
      "Seals",
      "Penguins",
    ],
  },
  {
    title: "Arcade",
    categories: [
      "Air-Hockey",
      "Arcade Basketball",
      "Arcade Boxing",
      "Billiards",
      "Cranes/Claw Machines",
      "Electronic Dark Boards",
      "Kiddle Rides",
      "Laser Maze",
      "Mini Bowling",
      "Pinball Machines",
      "Photo Booths",
      "Racing Games",
      "Skee-Ball",
      "Virtual Reality",
    ],
  },
  {
    title: "Art Gallery",
    categories: [
      "Commercial Gallery",
      "Artist-Run Initiative",
      "Vanity Gallery",
      "Non-Profit Gallery",
    ],
  },
  {
    title: "Bars & Clubs",
    categories: [
      "Irish Pub",
      "College Bar",
      "Nightclub",
      "Sports Bar",
      "Lounge",
      "Cigar Bar",
      "Dive Bar",
    ],
  },
  {
    title: "Bookstore",
    categories: [
      "Independent",
      "Bricks-and-Mortar",
      "Subscription",
      "Special Market",
      "Big Box",
    ],
  },
  {
    title: "Brewery",
    categories: [
      "Microbrewery",
      "Brewpub",
      "Taproom",
      "Regional",
      "Contract Brewing Company",
      "Alternating Proprietor",
    ],
  },
  {
    title: "Cafe",
    categories: [
      "Bakery",
      "Pastries",
      "Boba",
      "Coffee",
      "Tea",
      "Snacks",
      "Internet",
    ],
  },
  {
    title: "Casino",
    categories: [
      "Slots",
      "Video Poker",
      "Baccarat",
      "Blackjack",
      "Three Card Poker",
      "Four Card Poker",
      "Texas Hold 'Em",
      "Craps",
      "Roulette",
      "Specialty Games",
    ],
  },
  {
    title: "Coffee Shop",
    categories: [
      "Black",
      "Latte",
      "Cappuccino",
      "Americano",
      "Espresso",
      "Doppio",
      "Cortado",
      "Red Eye",
      "Galao",
      "Lungo",
      "Macchiato",
      "Mocha",
      "Ristretto",
      "Flat White",
      "Affogato",
      "Cafe au Lait",
      "Irish",
    ],
  },
  {
    title: "Convention",
    categories: [
      "Anime",
      "Comic",
      "Sci-Fi",
      "Gaming",
      "Literature",
      "Horror",
      "Technology",
    ],
  },
  {
    title: "Dessert",
    categories: [
      "Biscuits/Cookies",
      "Cakes",
      "Chocolates/Candies",
      "Custards/Puddings",
      "Deep-Fried Desserts",
      "Frozen Yogurt",
      "Ice Cream",
      "Gelato",
      "Sorbet",
      "Shaved Ice",
      "Jellied Desserts",
      "Pastries",
      "Pies",
    ],
  },
  {
    title: "Escape Room",
    categories: [
      "Linear Puzzles",
      "Non-Linear Puzzles",
      "Scavenger Hunt",
      "Red Herring",
      "Numbers and Texts",
      "Physical Puzzles",
      "Light and Sound",
      "Hidden Objects",
      "Visual Design",
      "Logic Puzzles",
      "Combination Puzzles",
    ],
  },
  {
    title: "Farmer's Market",
    categories: [
      "Indoor",
      "Outdoor",
      "Open-Air",
      "Organic",
      "Produce",
      "Homegrown",
      "Prepared Foods and Beverages",
    ],
  },
  {
    title: "Fast-food Restaurant",
    categories: [
      "Fish and Chips",
      "Sandwiches",
      "Pitas",
      "Pretzels",
      "Burgers",
      "Fried Chicken",
      "French Fries",
      "Onion Rings",
      "Chicken Nuggets",
      "Tacos",
      "Pizza",
      "Hot Dogs",
      "Ice Cream",
      "Sandwiches",
      "Subs",
      "Vegetarian",
      "American",
      "Chinese",
      "Mediterranean",
      "Mexican",
      "Japanese",
      "Filipino",
      "Indian",
      "Italian",
    ],
  },
  {
    title: "Fitness",
    categories: [
      "Dancing",
      "Aerobics",
      "Hiking",
      "Sports",
      "Gym",
      "Swimming",
      "Cycling",
      "Rowing",
    ],
  },
  {
    title: "Go Karting",
    categories: ["Indoor", "Outdoor", "Sprint", "Oval", "Enduro"],
  },
  {
    title: "Grocery",
    categories: [
      "Butcher",
      "Convenience Store",
      "Deli",
      "Greengrocer",
      "Health Food Store",
      "Milk Bar",
      "Supermarket",
      "Hypermarket",
      "Organic",
      "Self-Checkout",
    ],
  },
  {
    title: "Karaoke",
    categories: [
      "Refreshments",
      "Alcohol",
      "Videoke",
      "Rent by Hour",
      "Rent by Person",
    ],
  },
  {
    title: "Live Music",
    categories: [
      "Recital",
      "Theatrical",
      "Classical",
      "Festival",
      "Tour",
      "Lounge",
      "Jazz",
      "Rock",
      "EDM",
      "R&B",
      "Funk",
      "Country",
      "Latin",
      "Rap",
      "Reggae",
      "Hip Hop",
      "Polka",
    ],
  },
  {
    title: "Mall",
    categories: [
      "Regional Mall",
      "Super Regional",
      "Vertical Mall",
      "Strip Mall",
      "Dead Mall",
      "Outlet Mall",
      "Food Court",
      "Movie Theater",
    ],
  },
  {
    title: "Movies/Cinema",
    categories: ["IMAX", "3-D", "Arcade", "Matinee", "Student Discount"],
  },
  {
    title: "Museum",
    categories: [
      "Agricultural",
      "Architectural",
      "Archaeological",
      "Art",
      "Automobile",
      "Biographical",
      "Botanical Gardens",
      "Children's",
      "Community",
      "Design",
      "Encyclopedic",
      "Ethnographic",
      "Ethnological",
      "Historical Houses",
      "Historical Sites",
      "Living History",
      "Maritime",
      "Medical",
      "Memorial",
      "Military and War",
      "Mobile",
      "Natural History",
      "Science",
      "Virtual",
      "Zoological Parks",
    ],
  },
  {
    title: "Nature",
    categories: [
      "Park",
      "Hiking",
      "Garden",
      "Beach",
      "Forest",
      "Zipline",
      "Bridge",
    ],
  },
  {
    title: "Performing Arts",
    categories: [
      "Dance",
      "Music",
      "Opera",
      "Theatre",
      "Musical Theatre",
      "Classical",
      "Choral",
      "Magic",
      "Mime",
      "Puppetry",
      "Circus",
    ],
  },
  {
    title: "Pets/Animals",
    categories: ["Animal Reserve", "Zoo", "Animal Cafe"],
  },
  {
    title: "Recreation",
    categories: [
      "Backpacking",
      "Billiards",
      "Bowling",
      "Camping",
      "Canoeing",
      "Darts",
      "Fishing",
      "Golfing",
      "Hiking",
      "Ice Skating",
      "Kayaking",
      "Rowing",
      "Sailing/Boating",
      "Skiing",
      "Skydiving",
      "Surfboarding",
      "Swimming",
    ],
  },
  {
    title: "Seasonal",
    categories: ["Easter", "Christmas", "Thanksgiving", "Holiday"],
  },
  {
    title: "Sightseeing",
    categories: [
      "Historical Places",
      "Monuments",
      "Ancient Places",
      "Zoo",
      "Aquaria",
      "Museums",
      "Art Galleries",
      "Botanical Gardens",
      "Forts",
      "Castles",
      "Libraries",
      "Prisons",
      "Skyscrapers",
      "Bridges",
    ],
  },
  {
    title: "Sit-down Restaurant",
    categories: [
      "Fish and Chips",
      "Sandwiches",
      "Pitas",
      "Pretzels",
      "Burgers",
      "Fried Chicken",
      "French Fries",
      "Onion Rings",
      "Chicken Nuggets",
      "Tacos",
      "Pizza",
      "Hot Dogs",
      "Ice Cream",
      "Sandwiches",
      "Subs",
      "Vegetarian",
      "Buffet",
      "Fine Dining",
      "Bistro",
      "American",
      "Chinese",
      "Mediterranean",
      "Mexican",
      "Japanese",
      "Filipino",
      "Indian",
      "Italian",
    ],
  },
  {
    title: "Sports",
    categories: [
      "Basketball",
      "Football",
      "Soccer",
      "Tennis",
      "Athletics",
      "Volleyball",
      "Hockey",
      "Golf",
      "Martial Arts",
      "Badminton",
      "Table Tennis",
    ],
  },
  { title: "Tourism", categories: ["Gift Shop", "Curios", "Souvenirs"] },
  {
    title: "Water Sports",
    categories: [
      "Swimming",
      "Water Polo",
      "Jetski",
      "Wakeboarding",
      "Surfing",
      "Diving",
    ],
  },
  {
    title: "Winery",
    categories: [
      "White Wine",
      "Red Wine",
      "Riesling",
      "Pinot Gris",
      "Pinot Grigio",
      "Sauvignon Blanc",
      "Chardonnay",
      "Pinot Noir",
      "Zinfandel",
      "Syrah",
      "Cabernet Sauvignon",
    ],
  },
];
