export const moods = [
  { mood: "ambitious" },
  { mood: "calm" },
  { mood: "cheerful" },
  { mood: "chill" },
  { mood: "content" },
  { mood: "cool" },
  { mood: "energetic" },
  { mood: "exciting" },
  { mood: "fun" },
  { mood: "happy" },
  { mood: "humor" },
  { mood: "indoor" },
  { mood: "interesting" },
  { mood: "intimate" },
  { mood: "joyful" },
  { mood: "mellow" },
  { mood: "mysterious" },
  { mood: "open" },
  { mood: "outdoor" },
  { mood: "peaceful" },
  { mood: "positive" },
  { mood: "reflective" },
  { mood: "relaxed" },
  { mood: "romantic" },
  { mood: "silly" },
];
