export const cities = [
  { city: "Adelanto" },
  { city: "Agoura Hills" },
  { city: "Alameda" },
  { city: "Albany" },
  { city: "Alhambra" },
  { city: "Aliso Viejo" },
  { city: "Alturas" },
  { city: "Amador City" },
  { city: "American Canyon" },
  { city: "Anaheim" },
  { city: "Anderson" },
  { city: "Angels Camp" },
  { city: "Antioch" },
  { city: "Apple Valley" },
  { city: "Arcadia" },
  { city: "Arcata" },
  { city: "Arroyo Grande" },
  { city: "Artesia" },
  { city: "Arvin" },
  { city: "Atascadero" },
  { city: "Atherton" },
  { city: "Atwater" },
  { city: "Auburn" },
  { city: "Avalon" },
  { city: "Avenal" },
  { city: "Azusa" },
  { city: "Bakersfield" },
  { city: "Baldwin Park" },
  { city: "Banning" },
  { city: "Barstow" },
  { city: "Beaumont" },
  { city: "Bell" },
  { city: "Bell Gardens" },
  { city: "Bellflower" },
  { city: "Belmont" },
  { city: "Belvedere" },
  { city: "Benicia" },
  { city: "Berkeley" },
  { city: "Beverly Hills" },
  { city: "Big Bear Lake" },
  { city: "Biggs" },
  { city: "Bishop" },
  { city: "Blue Lake" },
  { city: "Blythe" },
  { city: "Bradbury" },
  { city: "Brawley" },
  { city: "Brea" },
  { city: "Brentwood" },
  { city: "Brisbane" },
  { city: "Buellton" },
  { city: "Buena Park" },
  { city: "Burbank" },
  { city: "Burlingame" },
  { city: "Calabasas" },
  { city: "Calexico" },
  { city: "California City" },
  { city: "Calimesa" },
  { city: "Calipatria" },
  { city: "Calistoga" },
  { city: "Camarillo" },
  { city: "Campbell" },
  { city: "Canyon Lake" },
  { city: "Capitola" },
  { city: "Carlsbad" },
  { city: "Carmel-by-the-Sea" },
  { city: "Carpinteria" },
  { city: "Carson" },
  { city: "Cathedral City" },
  { city: "Ceres" },
  { city: "Cerritos" },
  { city: "Chico" },
  { city: "Chino" },
  { city: "Chino Hills" },
  { city: "Chowchilla" },
  { city: "Chula Vista" },
  { city: "Citrus Heights" },
  { city: "Claremont" },
  { city: "Clayton" },
  { city: "Clearlake" },
  { city: "Cloverdale" },
  { city: "Clovis" },
  { city: "Coachella" },
  { city: "Coalinga" },
  { city: "Colfax" },
  { city: "Colma" },
  { city: "Colton" },
  { city: "Colusa" },
  { city: "Commerce" },
  { city: "Compton" },
  { city: "Concord" },
  { city: "Corcoran" },
  { city: "Corning" },
  { city: "Corona" },
  { city: "Coronado" },
  { city: "Corte Madera" },
  { city: "Costa Mesa" },
  { city: "Cotati" },
  { city: "Covina" },
  { city: "Crescent City" },
  { city: "Cudahy" },
  { city: "Culver City" },
  { city: "Cupertino" },
  { city: "Cypress" },
  { city: "Daly City" },
  { city: "Dana Point" },
  { city: "Danville" },
  { city: "Davis" },
  { city: "Del Mar" },
  { city: "Del Rey Oaks" },
  { city: "Delano" },
  { city: "Desert Hot Springs" },
  { city: "Diamond Bar" },
  { city: "Dinuba" },
  { city: "Dixon" },
  { city: "Dorris" },
  { city: "Dos Palos" },
  { city: "Downey" },
  { city: "Duarte" },
  { city: "Dublin" },
  { city: "Dunsmuir" },
  { city: "East Palo Alto" },
  { city: "Eastvale" },
  { city: "El Cajon" },
  { city: "El Centro" },
  { city: "El Cerrito" },
  { city: "El Monte" },
  { city: "El Segundo" },
  { city: "Elk Grove" },
  { city: "Emeryville" },
  { city: "Encinitas" },
  { city: "Escalon" },
  { city: "Escondido" },
  { city: "Etna" },
  { city: "Eureka" },
  { city: "Exeter" },
  { city: "Fairfax" },
  { city: "Fairfield" },
  { city: "Farmersville" },
  { city: "Ferndale" },
  { city: "Fillmore" },
  { city: "Firebaugh" },
  { city: "Folsom" },
  { city: "Fontana" },
  { city: "Fort Bragg" },
  { city: "Fort Jones" },
  { city: "Fortuna" },
  { city: "Foster City" },
  { city: "Fountain Valley" },
  { city: "Fowler" },
  { city: "Fremont" },
  { city: "Fresno" },
  { city: "Fullerton" },
  { city: "Galt" },
  { city: "Garden Grove" },
  { city: "Gardena" },
  { city: "Gilroy" },
  { city: "Glendale" },
  { city: "Glendora" },
  { city: "Goleta" },
  { city: "Gonzales" },
  { city: "Grand Terrace" },
  { city: "Grass Valley" },
  { city: "Greenfield" },
  { city: "Gridley" },
  { city: "Grover Beach" },
  { city: "Guadalupe" },
  { city: "Gustine" },
  { city: "Half Moon Bay" },
  { city: "Hanford" },
  { city: "Hawaiian Gardens" },
  { city: "Hawthorne" },
  { city: "Hayward" },
  { city: "Healdsburg" },
  { city: "Hemet" },
  { city: "Hercules" },
  { city: "Hermosa Beach" },
  { city: "Hesperia" },
  { city: "Hidden Hills" },
  { city: "Highland" },
  { city: "Hillsborough" },
  { city: "Hollister" },
  { city: "Holtville" },
  { city: "Hughson" },
  { city: "Huntington Beach" },
  { city: "Huntington Park" },
  { city: "Huron" },
  { city: "Imperial" },
  { city: "Imperial Beach" },
  { city: "Indian Wells" },
  { city: "Indio" },
  { city: "Industry" },
  { city: "Inglewood" },
  { city: "Ione" },
  { city: "Irvine" },
  { city: "Irwindale" },
  { city: "Isleton" },
  { city: "Jackson" },
  { city: "Jurupa Valley" },
  { city: "Kerman" },
  { city: "King City" },
  { city: "Kingsburg" },
  { city: "La Canada Flintridge" },
  { city: "La Habra" },
  { city: "La Habra Heights" },
  { city: "La Mesa" },
  { city: "La Mirada" },
  { city: "La Palma" },
  { city: "La Puente" },
  { city: "La Quinta" },
  { city: "La Verne" },
  { city: "Lafayette" },
  { city: "Laguna Beach" },
  { city: "Laguna Hills" },
  { city: "Laguna Niguel" },
  { city: "Laguna Woods" },
  { city: "Lake Elsinore" },
  { city: "Lake Forest" },
  { city: "Lakeport" },
  { city: "Lakewood" },
  { city: "Lancaster" },
  { city: "Larkspur" },
  { city: "Lathrop" },
  { city: "Lawndale" },
  { city: "Lemon Grove" },
  { city: "Lemoore" },
  { city: "Lincoln" },
  { city: "Lindsay" },
  { city: "Live Oak" },
  { city: "Livemore" },
  { city: "Livingston" },
  { city: "Lodi" },
  { city: "Loma Linda" },
  { city: "Lomita" },
  { city: "Lompoc" },
  { city: "Long Beach" },
  { city: "Loomis" },
  { city: "Los Alamitos" },
  { city: "Los Altos" },
  { city: "Los Altos Hills" },
  { city: "Los Angeles" },
  { city: "Los Banos" },
  { city: "Los Gatos" },
  { city: "Loyalton" },
  { city: "Lynwood" },
  { city: "Madera" },
  { city: "Malibu" },
  { city: "Mammoth Lakes" },
  { city: "Manhattan Beach" },
  { city: "Manteca" },
  { city: "Maricopa" },
  { city: "Marina" },
  { city: "Martinez" },
  { city: "Marysville" },
  { city: "Maywood" },
  { city: "McFarland" },
  { city: "Mendota" },
  { city: "Menifee" },
  { city: "Menlo Park" },
  { city: "Merced" },
  { city: "Mill Valley" },
  { city: "Millbrae" },
  { city: "Milpitas" },
  { city: "Mission Viejo" },
  { city: "Modesto" },
  { city: "Monrovia" },
  { city: "Montague" },
  { city: "Montclair" },
  { city: "Monte Sereno" },
  { city: "Montebello" },
  { city: "Monterey" },
  { city: "Monterey Park" },
  { city: "Moorpark" },
  { city: "Moraga" },
  { city: "Moreno Valley" },
  { city: "Morgan Hill" },
  { city: "Morro Bay" },
  { city: "Mount Shasta" },
  { city: "Mountain View" },
  { city: "Murrieta" },
  { city: "Napa" },
  { city: "National City" },
  { city: "Needles" },
  { city: "Nevada City" },
  { city: "Newark" },
  { city: "Newman" },
  { city: "Newport Beach" },
  { city: "Norco" },
  { city: "Norwalk" },
  { city: "Novato" },
  { city: "Oakdale" },
  { city: "Oakland" },
  { city: "Oakley" },
  { city: "Oceanside" },
  { city: "Ojai" },
  { city: "Ontario" },
  { city: "Orange" },
  { city: "Orange Cove" },
  { city: "Orinda" },
  { city: "Orland" },
  { city: "Oroville" },
  { city: "Oxnard" },
  { city: "Pacific Grove" },
  { city: "Pacifica" },
  { city: "Palm Desert" },
  { city: "Palm Springs" },
  { city: "Palmdale" },
  { city: "Palo Alto" },
  { city: "Palos Verdes Estates" },
  { city: "Paradise" },
  { city: "Paramount" },
  { city: "Parlier" },
  { city: "Pasadena" },
  { city: "Paso Robles" },
  { city: "Patterson" },
  { city: "Perris" },
  { city: "Petaluma" },
  { city: "Pico Rivera" },
  { city: "Piedmont" },
  { city: "Pinole" },
  { city: "Pismo Beach" },
  { city: "Pittsburg" },
  { city: "Placentia" },
  { city: "Placerville" },
  { city: "Pleasant Hill" },
  { city: "Pleasanton" },
  { city: "Plymouth" },
  { city: "Point Arena" },
  { city: "Pomona" },
  { city: "Port Hueneme" },
  { city: "Porterville" },
  { city: "Portola" },
  { city: "Portola Valley" },
  { city: "Poway" },
  { city: "Ramona" },
  { city: "Rancho Cordova" },
  { city: "Rancho Cucamonga" },
  { city: "Rancho Mirage" },
  { city: "Rancho Palos Verdes" },
  { city: "Rancho Santa Margarita" },
  { city: "Red Bluff" },
  { city: "Redding" },
  { city: "Redlands" },
  { city: "Redondo Beach" },
  { city: "Redwood City" },
  { city: "Reedley" },
  { city: "Rialto" },
  { city: "Richmond" },
  { city: "Ridgecrest" },
  { city: "Rio Dell" },
  { city: "Rio Vista" },
  { city: "Ripon" },
  { city: "Riverbank" },
  { city: "Riverside" },
  { city: "Rocklin" },
  { city: "Rohnert Park" },
  { city: "Rolling Hills" },
  { city: "Rolling Hills Estates" },
  { city: "Rosemead" },
  { city: "Roseville" },
  { city: "Ross" },
  { city: "Rowland Heights" },
  { city: "Sacramento" },
  { city: "St. Helena" },
  { city: "Salinas" },
  { city: "San Anselmo" },
  { city: "San Bernardino" },
  { city: "San Bruno" },
  { city: "San Carlos" },
  { city: "San Clemente" },
  { city: "San Diego" },
  { city: "San Dimas" },
  { city: "San Fernando" },
  { city: "San Francisco" },
  { city: "San Gabriel" },
  { city: "San Jacinto" },
  { city: "San Joaquin" },
  { city: "San Jose" },
  { city: "San Juan Bautista" },
  { city: "San Juan Capistrano" },
  { city: "San Leandro" },
  { city: "San Luis Obispo" },
  { city: "San Marcos" },
  { city: "San Marino" },
  { city: "San Mateo" },
  { city: "San Pablo" },
  { city: "San Rafael" },
  { city: "San Ramon" },
  { city: "Sand City" },
  { city: "Sanger" },
  { city: "Santa Ana" },
  { city: "Santa Barbara" },
  { city: "Santa Clara" },
  { city: "Santa Clarita" },
  { city: "Santa Cruz" },
  { city: "Santa Fe Springs" },
  { city: "Santa Maria" },
  { city: "Santa Monica" },
  { city: "Santa Paula" },
  { city: "Santa Rosa" },
  { city: "Santee" },
  { city: "Saratoga" },
  { city: "Sausalito" },
  { city: "Scotts Valley" },
  { city: "Seal Beach" },
  { city: "Seaside" },
  { city: "Sebastopol" },
  { city: "Selma" },
  { city: "Shafter" },
  { city: "Shasta Lake" },
  { city: "Sierra Madre" },
  { city: "Signal Hill" },
  { city: "Simi Valley" },
  { city: "Solana Beach" },
  { city: "Soledad" },
  { city: "Solvang" },
  { city: "Sonoma" },
  { city: "Sonora" },
  { city: "South El Monte" },
  { city: "South Gate" },
  { city: "South Lake Tahoe" },
  { city: "South Pasadena" },
  { city: "South San Francisco" },
  { city: "Stanton" },
  { city: "Stockton" },
  { city: "Suisun City" },
  { city: "Sunnyvale" },
  { city: "Susanville" },
  { city: "Sutter Creek" },
  { city: "Taft" },
  { city: "Tehachapi" },
  { city: "Tehama" },
  { city: "Temecula" },
  { city: "Temple City" },
  { city: "Thousand Oaks" },
  { city: "Tiburon" },
  { city: "Torrance" },
  { city: "Tracy" },
  { city: "Trinidad" },
  { city: "Truckee" },
  { city: "Tulare" },
  { city: "Tulelake" },
  { city: "Turlock" },
  { city: "Tustin" },
  { city: "Twentynine Palms" },
  { city: "Ukiah" },
  { city: "Union City" },
  { city: "Upland" },
  { city: "Vacaville" },
  { city: "Vallejo" },
  { city: "Ventura" },
  { city: "Vernon" },
  { city: "Victorville" },
  { city: "Villa Park" },
  { city: "Visalia" },
  { city: "Vista" },
  { city: "Walnut" },
  { city: "Walnut Creek" },
  { city: "Wasco" },
  { city: "Waterford" },
  { city: "Watsonville" },
  { city: "Weed" },
  { city: "West Covina" },
  { city: "West Hollywood" },
  { city: "West Sacramento" },
  { city: "Westlake Village" },
  { city: "Westminster" },
  { city: "Westmorland" },
  { city: "Wheatland" },
  { city: "Whittier" },
  { city: "Wildomar" },
  { city: "Williams" },
  { city: "Willits" },
  { city: "Willows" },
  { city: "Windsor" },
  { city: "Winters" },
  { city: "Woodlake" },
  { city: "Woodland" },
  { city: "Woodside" },
  { city: "Yorba Linda" },
  { city: "Yountville" },
  { city: "Yreka" },
  { city: "Yuba City" },
  { city: "Yucaipa" },
  { city: "Yucca Valley" },
];
