export const industries = [
  { title: "Amusement Park" },
  { title: "Apparel" },
  { title: "Aquarium" },
  { title: "Arcade" },
  { title: "Art Gallery" },
  { title: "Bars & Clubs" },
  { title: "Bookstore" },
  { title: "Brewery" },
  { title: "Cafe" },
  { title: "Casino" },
  { title: "Coffee Shop" },
  { title: "Convention" },
  { title: "Dessert" },
  { title: "Escape Room" },
  { title: "Farmer's Market" },
  { title: "Fast-food Restaurant" },
  { title: "Fitness" },
  { title: "Go Karting" },
  { title: "Grocery" },
  { title: "Karaoke" },
  { title: "Live Music" },
  { title: "Mall" },
  { title: "Movies/Cinema" },
  { title: "Museum" },
  { title: "Nature" },
  { title: "Performing Arts" },
  { title: "Pets/Animals" },
  { title: "Recreation" },
  { title: "Seasonal" },
  { title: "Sightseeing" },
  { title: "Sit-down Restaurant" },
  { title: "Sports" },
  { title: "Sports Bar" },
  { title: "Sports Event" },
  { title: "Theme Park" },
  { title: "Tourism" },
  { title: "Water Sports" },
  { title: "Winery" },
];
